rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - rbx-2
  - jruby
gemfile:
  - gemfiles/activesupport_3.2.gemfile
  - gemfiles/activesupport_4.0.gemfile
  - gemfiles/activesupport_4.1.gemfile
matrix:
  allow_failures:
    - rvm: rbx-2
